### ISSUE TITLE
I don't know how to get the validation set of this project

### ISSUE THREAD

**Issue by mmmmmomo** [pinakinathc/multiviewsketch-garment#1]
@pinakinathc 
I saw your project and was very interested in it, but I encountered some problems in the process of trying to run it.

```
Original Traceback (most recent call last):
  File "D:\anaconda\envs\garment\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda\envs\garment\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\garment\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\multiviewsketch-garment-main\src\dataset.py", line 66, in __getitem__
    garment = self.all_garments[index]
IndexError: list index out of range
```
I guess it's the lack of verification set.
It seems that I need to place the corresponding . obj file in the GEO/OBJ folder and write the file name to be used as the verification set in the val.txt file
But I can't find the corresponding obj file in the data set you provided to put it in the GEO/OBJ folder and val.txt.
Sorry to bother you ! but I really want to know what data and files need to be prepared before the project runs and how to operate the project.
English is not my native language. Please forgive me for any inadequacy if there is something that can not be expressed properly.

**Comment by pinakinathc** [comment]
Hi @mmmmmomo 
Maybe this is not a valid issue anymore. Nonetheless, here is the val.txt file -- uploading here for future use.
Note, I only store the IDs from the Siggraph-Asia-15 dataset used in the paper.
[val.txt](https://github.com/pinakinathc/multiviewsketch-garment/files/15134176/val.txt)

**Comment by mmmmmomo** [comment]
Thanks a lot!
